import "./globals.css";
import type { Metadata } from "next";
import { Livvic } from "next/font/google";

const livvic = Livvic({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={livvic.className}>{children}</body>
    </html>
  );
}
